column_dtypes = [{'street': str,
                  'city': str,
                  'state': str,
                  'ticket_number': str,
                  'ticket_issue_date': str,
                  'ticket_issue_time': str,
                  'violation_external_code': str,
                  'violation_desc_long': str,
                  'street_no': str,
                  'street_name': str,
                  'street_suffix': str,
                  'fine_amount': str,
                  'badge__': str,
                  'Unnamed: 13': str,
                  '[sequence]': int,
                  '[summary]': str,
                  '[addressee]': str,
                  '[delivery_line_1]': str,
                  '[delivery_line_2]': str,
                  '[city_name]': str,
                  '[state_abbreviation]': str,
                  '[full_zipcode]': str,
                  '[notes]': str,
                  '[county_name]': str,
                  '[rdi]': str,
                  '[latitude]': float,
                  '[longitude]': float,
                  '[precision]': str,
                  '[dpv_match_code]': str,
                  '[dpv_footnotes]': str,
                  '[footnotes]': str,
                  '[county_fips]': str,
                  '[record_type]': str,
                  '[zip_type]': str,
                  '[carrier_route]': str,
                  '[congressional_district]': str,
                  '[building_default_indicator]': str,
                  '[elot_sequence]': str,
                  '[elot_sort]': str,
                  '[time_zone]': str,
                  '[utc_offset]': str,
                  '[dst]': str,
                  '[dpv_cmra]': str,
                  '[ews_match]': str,
                  '[lacslink_indicator]': str,
                  '[lacslink_code]': str,
                  '[suitelink_match]': str,
                  '[dpv_vacant]': str,
                  '[active]': str,
                  '[urbanization]': str,
                  '[primary_number]': str,
                  '[street_name]': str,
                  '[street_predirection]': str,
                  '[street_postdirection]': str,
                  '[street_suffix]': str,
                  '[secondary_number]': str,
                  '[secondary_designator]': str,
                  '[extra_secondary_number]': str,
                  '[extra_secondary_designator]': str,
                  '[pmb_designator]': str,
                  '[pmb_number]': str,
                  '[default_city_name]': str,
                  '[zipcode]': str,
                  '[plus4_code]': str,
                  '[delivery_point]': str,
                  '[delivery_point_check_digit]': str,
                  '[last_line]': str,
                  '[delivery_point_barcode]': str},

                 {'street': str,
                  'city': str,
                  'state': str,
                  'Ticket Number': str,
                  'Ticket Issue Date': str,
                  'Ticket Issue Time': str,
                  'Violation External Code': str,
                  'Violation Desc Long': str,
                  'Street No': str,
                  'Street Name': str,
                  'Street Suffix': str,
                  'Fine Amount': str,
                  'Badge #': str,
                  'Unnamed: 13': str,
                  '[sequence]': int,
                  '[summary]': str,
                  '[addressee]': str,
                  '[delivery_line_1]': str,
                  '[delivery_line_2]': str,
                  '[city_name]': str,
                  '[state_abbreviation]': str,
                  '[full_zipcode]': str,
                  '[notes]': str,
                  '[county_name]': str,
                  '[rdi]': str,
                  '[latitude]': float,
                  '[longitude]': float,
                  '[precision]': str,
                  '[dpv_match_code]': str,
                  '[dpv_footnotes]': str,
                  '[footnotes]': str,
                  '[county_fips]': str,
                  '[record_type]': str,
                  '[zip_type]': str,
                  '[carrier_route]': str,
                  '[congressional_district]': str,
                  '[building_default_indicator]': str,
                  '[elot_sequence]': str,
                  '[elot_sort]': str,
                  '[time_zone]': str,
                  '[utc_offset]': str,
                  '[dst]': str,
                  '[dpv_cmra]': str,
                  '[ews_match]': str,
                  '[lacslink_indicator]': str,
                  '[lacslink_code]': str,
                  '[suitelink_match]': str,
                  '[dpv_vacant]': str,
                  '[active]': str,
                  '[urbanization]': str,
                  '[primary_number]': str,
                  '[street_name]': str,
                  '[street_predirection]': str,
                  '[street_postdirection]': str,
                  '[street_suffix]': str,
                  '[secondary_number]': str,
                  '[secondary_designator]': str,
                  '[extra_secondary_number]': str,
                  '[extra_secondary_designator]': str,
                  '[pmb_designator]': str,
                  '[pmb_number]': str,
                  '[default_city_name]': str,
                  '[zipcode]': str,
                  '[plus4_code]': str,
                  '[delivery_point]': str,
                  '[delivery_point_check_digit]': str,
                  '[last_line]': str,
                  '[delivery_point_barcode]': str
                 }
                ]
